baseURL = 'https://spaceconquest.ai/'
languageCode = 'en-us'
title = 'Space Conquest AI'

[build]
  writeStats = true

[params]
  assetsDir = "assets"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1

  [languages.eo]
    languageName = "Esperanto"

  [languages.es]
    languageName = "Español"

  [languages.fr]
    languageName = "Français"

  [languages.ja]
    languageName = "日本語"

  [languages.zh]
    languageName = "简体中文"